name: Brocken rear brakes

on:
 push:
  branches:
  - main
 pull_request:
  branches:
   - main

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: lounch test
     uses: action/checkout@v4

   - name: setup Python
     uses: action/setup-python@v4
     with:
       python_version: '3.10'

   - name: install dependencies
     run: |
       pip install -r requirements.txt
       
   - name: go pytest
     run: pytest
